version: '3'

services:
  c2:
    container_name: arsenal_c2
    build: './'
    ports:
      - "80:80"
    environment:
      - TEAMSERVER_URI=http://redteam-arsenal.com
      - API_KEY_FILE=/opt/arsenal-c2/.arsenal_key

